### ISSUE TITLE
Deployment from HTTP repo fails with 'Failed to create target directory'

### ISSUE THREAD

**Issue by quinnbailey** [DeployHubProject/DeployHub-Pro#175]
Credentials have all necessary permissions, however deployment still fails.  Apparently @pgibbs-openmake knows the details of exactly why this happening.  One thing that particularly bothers me about this issue is that I was not seeing failure messages in the webadmin while performing this deployment, only when I ran from the command line.

**Comment by pgibbs-openmake** [comment]
"Failed to create target directory" is a red-herring. We saw this when running the deployment from the command line. The reason THAT failed was that the underlying protocol_cd call was failing when run as root because it failed to find sshexec (which does a mkdir;cd;pwd combination). We needed to set DM_TARGET_USER to omreleng in order for the engine to switch user properly and then it just didn't transfer any files (even though the checkout operation had stated 1 file checked out).

The issue turns out to be in the HTTP Repository plug-in. If the target file is to be placed in a sub-directory (in this case "webadmin") the file-get-write routine will fail if the sub-directory does not exist in the dropzone. It makes no attempt to create the required sub-directory. This results in a failure to create the dropzone file and thus no files are transferred.

Solution is to fix the HTTP Repository plug-in to create sub-folders as and when they are required. It would also be a good idea to throw a runtime error if the file creation fails. At the moment this error is effectively ignored which is why the output log does not report the failure.
