### ISSUE TITLE
Global activities missing

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#251]
Old:
![image](https://user-images.githubusercontent.com/11614204/61786784-196eda00-ae2c-11e9-9fad-78aa02c490ab.png)

New:
![image](https://user-images.githubusercontent.com/11614204/61786838-30153100-ae2c-11e9-8081-1cdc49a28617.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
Changed the query logic to load the functions and procedures that are defined at the GLOBAL level into the Global Activities.  These functions and procedures will also be listed under the GLOBAL domain (ie duplicated).  You can choose from either location in the tree.

`docker pull quay.io/deployhub/deployhub-pro@sha256:cf186b1ee1ff23860d8e7fdcc6a90bdbb8f50fff2e79269c1c904be8c617e034`

**Comment by piyush94** [comment]
What i meant by global activities missing was the built in procedures such as if-else, echo, etc are no more available. Have they been removed?
![image](https://user-images.githubusercontent.com/11614204/62027433-5277c780-b1fb-11e9-8bd6-31f83c90b7e4.png)

**Comment by sbtaylor15** [comment]
Reworked the query to return the built-in functions at the Global level.  One outstanding item is on the Functions/Procedure Explorer Tab,  the built-in function categories show up at the Global level even though there are no children present.  All other tree views are working as expected just this one has a extra categories.  Otherwise it is working as expected.

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:982c40417b54d57250fd874e15548d40ddfc7c780f43a09097714de73ca98835

**Comment by piyush94** [comment]
The view is visible now.
CC: @svisagan83

**Comment by sbtaylor15** [comment]
Cleaned up the Procedures and Functions Tree to not show built-in categories that are empty.

CC: @svisagan83

docker pull quay.io/deployhub/deployhub-pro@sha256:7b4c3289a8b692b4e9817dfad4846b51233a266399c7e63acd20e6799a99035d
