### ISSUE TITLE
All repositories not visible when creating component

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#285]
All repositories not visible when creating component. Only GLOBAL level repos are visible.

CC: @svisagan83

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/70518356-38160900-1b60-11ea-943f-c449aaec3d95.png)

![image](https://user-images.githubusercontent.com/11614204/70518377-43693480-1b60-11ea-85e5-cfe013007964.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 what is the userid and which groups does the user belongs to?  It looks like a permissions issue.
Also, what are the permissions set to on the repo?

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - please pull the latest image.  We changed the logic on how the inherited access is being resolved.  

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - thanks. It's working now.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - now sub-domain users not able to create components in any of their sub-domains.
![image](https://user-images.githubusercontent.com/11614204/70775354-3dae6180-1da1-11ea-80dc-a068aa85bfec.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - what are the permissions set to for the Blockchain group?  And what are the users groups?

 CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - what are the permissions set to for the Blockchain group?  And what are the users groups?

 CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we found the issue.  It only happens when the GLOBAL domain is set to "read only" for the user since they belong to "custom" group.  The component was initially being created in GLOBAL and then moved to the proper domain as part of the same.  The error doesn't show up if you have write permissions to GLOBAL.  We removed the extra step and now the component is created directly in the selected domain.  Please pull the latest image.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 - Can we close this issue?

CC: @svisagan83
