### ISSUE TITLE
Global components not visible

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#296]
Hi, Global components with access level as Everyone are not visible to the user of a sub-domain.
All the other objects defined at Global with Everyone access are visible such as credentials, repositories, etc.

Can this be fixed at priority?
Thanks.

CC: @svisagan83

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/76395337-174a9300-639d-11ea-8e2e-b92fcbabc7d9.png)

Global components not visible

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/76396002-6d6c0600-639e-11ea-9283-28752bc83064.png)

This was there earlier.

**Comment by sbtaylor15** [comment]
@piyush94 - we will take a look at this.  We are trying to nail down the pattern when it works and when it doesn't since we have application version in which it is working fine and others has it where they are missing.

**Comment by piyush94** [comment]
@sbtaylor15 - Some more details.
Application in sub-domain
User is in sub-domain

User from sub-domain is able to see other objects on which i have set access level Everyone

Component is in GLOBAL domain.

Interestingly, it's visible in the components page, when i login as sub-domain user
![image](https://user-images.githubusercontent.com/11614204/76427234-0ec07f80-63d2-11ea-892b-d5099ed57eb9.png)

**Comment by sbtaylor15** [comment]
@piyush94 we think we have found the scenario.  In the current version, it will work correctly if you navigate to the Actions tab and select an Activity from the tree view on the right.  Then go to the Application Version and the Component Versions should show Global.  We have updated the code to add in the missing data that the select was providing.  

We have tested this on multiple installs with 2 or 3 working as expected.  We believe that 3rd one is not showing correctly due to bad test data in our database.  Please confirm that its working correctly on your side.  

Please pull the latest image for this update.  

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - now only Global components are visible, when i login as sub-domain user.
![image](https://user-images.githubusercontent.com/11614204/76726012-f35cc800-6775-11ea-9c99-f1e42474208e.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we were able to recreate the last issue and have fixed it.  Please pull the latest image.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 - it's working.

CC: @svisagan83
