### ISSUE TITLE
scripts not executing with custom action

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#305]
Working fine with Pre and Post Action.
With Custom Action getting below error:

![image](https://user-images.githubusercontent.com/11614204/79437508-e4c13500-7fef-11ea-9a4c-70bcf4307882.png)

Procedures:
![image](https://user-images.githubusercontent.com/11614204/79437578-002c4000-7ff0-11ea-9e05-7eb8e0997295.png)

and

![image](https://user-images.githubusercontent.com/11614204/79437615-11754c80-7ff0-11ea-910b-4b245a99e132.png)

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 it looks like the custom action is pushing an additional environment variable that isn't valid for the shell,  ?customcomp117=Y.  Let us do some debugging on this since we have logic in place to avoid this.  Need to figure out how that variable is being passed to the shell.

CC: @svisagan83

**Comment by sbtaylor15** [comment]
@piyush94 we updated dmtransfer to exclude vars with ? from being passed to the remote shell.

From:
```
            value = line.split("=", 1)[-1]
            remote_env[key] = value
```
To:
```
            value = line.split("=", 1)[-1]
            if ("?" not in key):
                remote_env[key] = value
```

Latest image has the update.

CC: @svisagan83

**Comment by piyush94** [comment]
@sbtaylor15 thanks, it's working now.

CC: @svisagan83
